create column table shenzhen_sorted  as (select * from  "TUK3_TS_MJ"."SHENZHEN_CLEAN" order by id, seconds);
alter table shenzhen_sorted add ( rid int GENERATED BY DEFAULT AS IDENTITY);
ALTER TABLE shenzhen_sorted ADD PRIMARY KEY (rid)